# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sihipo_root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
        ),
        migrations.CreateModel(
            name='PlantAlert',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Waktu')),
                ('url', models.CharField(default='#', max_length=255, verbose_name='URL Aksi')),
                ('state', models.CharField(blank=True, choices=[(None, 'N/A'), ('N', 'Notice'), ('W', 'Warning'), ('S', 'Severe')], max_length=2, null=True, verbose_name='Status')),
            ],
            options={
                'ordering': ['-dt'],
                'verbose_name': 'Berita Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantControlDetail',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(choices=[(None, 'N/A'), ('D0', 'Digital 0'), ('D1', 'Digital 1'), ('D2', 'Digital 2'), ('D3', 'Digital 3'), ('D4', 'Digital 4'), ('D5', 'Digital 5'), ('D6', 'Digital 6'), ('D7', 'Digital 7')], max_length=3, verbose_name='Kode')),
                ('val', models.CharField(blank=True, choices=[(None, 'N/A'), ('L', 'GROW LAMP'), ('S', 'SPRAY'), ('W', 'WATER PUMP'), ('A', 'AERIAL'), ('B', 'BLOWER')], max_length=2, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'Detail Control Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantControlLog',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Waktu')),
                ('state', models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('P', 'To Do / Progress'), ('C', 'Done / Complete')], max_length=2, null=True, verbose_name='Status')),
            ],
            options={
                'ordering': ['-dt'],
                'verbose_name': 'Log Kontrol Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantControlLogDetail',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(choices=[(None, 'N/A'), ('D0', 'Digital 0'), ('D1', 'Digital 1'), ('D2', 'Digital 2'), ('D3', 'Digital 3'), ('D4', 'Digital 4'), ('D5', 'Digital 5'), ('D6', 'Digital 6'), ('D7', 'Digital 7')], max_length=3, verbose_name='Kode')),
                ('val', models.BooleanField(verbose_name='Nilai')),
                ('plant_control_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControlLog', verbose_name='Log Kontrol Tanaman')),
            ],
            options={
                'verbose_name': 'Detail Log Control Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantDevice',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Device')),
                ('url', models.URLField(unique=True, verbose_name='URL Device')),
                ('tipe', models.CharField(choices=[(None, 'N/A'), ('SIHIPO_C', 'Device Kontrol'), ('SIHIPO_S', 'Device Device')], max_length=10, verbose_name='Tipe Device')),
            ],
            options={
                'verbose_name': 'Device Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantEval',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
            ],
            options={
                'verbose_name': 'Evaluasi Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantEvalIf',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode IF')),
                ('eval_if', models.TextField(unique=True, verbose_name='Evaluate IF')),
            ],
            options={
                'verbose_name': 'Evaluasi Tanaman (IF)',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantEvalLog',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Waktu')),
                ('plant_eval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEval', verbose_name='Evaluasi Tanaman')),
            ],
            options={
                'ordering': ['-dt'],
                'verbose_name': 'Log Evaluasi Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantEvalThen',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode THEN')),
                ('eval_then', models.TextField(unique=True, verbose_name='Evaluate THEN')),
            ],
            options={
                'verbose_name': 'Evaluasi Tanaman (THEN)',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantOpt',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('usia', models.FloatField(default=0, verbose_name='Usia Hari')),
            ],
            options={
                'verbose_name': 'Kondisi Optimal Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantOptDetail',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(choices=[(None, 'N/A'), ('PH', 'Keasaman'), ('EC', 'Konduktifitas'), ('HT', 'Kelembapan'), ('TW', 'Suhu Air'), ('TA', 'Suhu Udara'), ('LW', 'Level Air')], max_length=3, verbose_name='Kode')),
                ('val', models.FloatField(verbose_name='Nilai')),
                ('tol', sihipo_root.models.FloatRangeField(default=10, verbose_name='Toleransi (%)')),
                ('plant_opt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantOpt', verbose_name='Kondisi Optimal Tanaman')),
            ],
            options={
                'verbose_name': 'Detail Kondisi Optimal Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantPlant',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Tanaman')),
            ],
            options={
                'verbose_name': 'Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantRack',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(max_length=20, verbose_name='Kode Rak')),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Tanggal Pasang')),
                ('p', models.FloatField(blank=True, null=True, verbose_name='Panjang')),
                ('l', models.FloatField(blank=True, null=True, verbose_name='Lebar')),
                ('t', models.FloatField(blank=True, null=True, verbose_name='Tinggi')),
                ('type', models.CharField(blank=True, choices=[(None, 'N/A'), ('NFT', 'Net Film'), ('DFT', 'Deep Flow'), ('WICK', 'Wick')], max_length=4, null=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Rak Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantRackPoint',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Tanggal Tanam')),
                ('p', models.FloatField(blank=True, null=True, verbose_name='Panjang')),
                ('l', models.FloatField(blank=True, null=True, verbose_name='Lebar')),
                ('t', models.FloatField(blank=True, null=True, verbose_name='Tinggi')),
                ('plant_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantPlant', verbose_name='Tanaman')),
                ('plant_rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman')),
            ],
            options={
                'verbose_name': 'Point Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantSensorDetail',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(choices=[(None, 'N/A'), ('PH', 'Keasaman'), ('EC', 'Konduktifitas'), ('HT', 'Kelembapan'), ('TW', 'Suhu Air'), ('TA', 'Suhu Udara'), ('LW', 'Level Air')], max_length=3, verbose_name='Kode')),
            ],
            options={
                'verbose_name': 'Detail Sensor Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantSensorLog',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Waktu')),
                ('state', models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('P', 'To Do / Progress'), ('C', 'Done / Complete')], max_length=2, null=True, verbose_name='Status')),
                ('plant_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman')),
            ],
            options={
                'ordering': ['-dt'],
                'verbose_name': 'Log Sensor Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.CreateModel(
            name='PlantSensorLogDetail',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(choices=[(None, 'N/A'), ('PH', 'Keasaman'), ('EC', 'Konduktifitas'), ('HT', 'Kelembapan'), ('TW', 'Suhu Air'), ('TA', 'Suhu Udara'), ('LW', 'Level Air')], max_length=3, verbose_name='Kode')),
                ('val', models.FloatField(blank=True, null=True, verbose_name='Nilai')),
                ('plant_sensor_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensorLog', verbose_name='Log Sensor Tanaman')),
            ],
            options={
                'verbose_name': 'Detail Log Sensor Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
        migrations.AddField(
            model_name='plantbase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantbase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlantControl',
            fields=[
                ('plantdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantDevice')),
            ],
            options={
                'verbose_name': 'Kontrol Tanaman',
            },
            bases=('sihipo_root.plantdevice',),
        ),
        migrations.CreateModel(
            name='PlantSensor',
            fields=[
                ('plantdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantDevice')),
            ],
            options={
                'verbose_name': 'Sensor Tanaman',
            },
            bases=('sihipo_root.plantdevice',),
        ),
        migrations.AddField(
            model_name='plantopt',
            name='plant_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantPlant', verbose_name='Tanaman'),
        ),
        migrations.AddField(
            model_name='planteval',
            name='plant_eval_if',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEvalIf', verbose_name='Evaluasi Tanaman (IF)'),
        ),
        migrations.AddField(
            model_name='planteval',
            name='plant_eval_then',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEvalThen', verbose_name='Evaluasi Tanaman (THEN)'),
        ),
        migrations.AddField(
            model_name='plantcontrollog',
            name='plant_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
        migrations.AlterUniqueTogether(
            name='plantsensorlogdetail',
            unique_together=set([('plant_sensor_log', 'kode')]),
        ),
        migrations.AddField(
            model_name='plantsensorlog',
            name='plant_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensor', verbose_name='Sensor Tanaman'),
        ),
        migrations.AddField(
            model_name='plantsensordetail',
            name='plant_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensor', verbose_name='Sensor Tanaman'),
        ),
        migrations.AddField(
            model_name='plantrack',
            name='plant_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControl', verbose_name='Kontrol Tanaman'),
        ),
        migrations.AddField(
            model_name='plantrack',
            name='plant_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensor', verbose_name='Sensor Tanaman'),
        ),
        migrations.AlterUniqueTogether(
            name='plantoptdetail',
            unique_together=set([('plant_opt', 'kode')]),
        ),
        migrations.AlterUniqueTogether(
            name='plantopt',
            unique_together=set([('plant_plant', 'usia')]),
        ),
        migrations.AlterUniqueTogether(
            name='planteval',
            unique_together=set([('plant_eval_if', 'plant_eval_then')]),
        ),
        migrations.AlterUniqueTogether(
            name='plantcontrollogdetail',
            unique_together=set([('plant_control_log', 'kode')]),
        ),
        migrations.AddField(
            model_name='plantcontrollog',
            name='plant_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControl', verbose_name='Kontrol Tanaman'),
        ),
        migrations.AddField(
            model_name='plantcontroldetail',
            name='plant_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControl', verbose_name='Kontrol Tanaman'),
        ),
        migrations.AlterUniqueTogether(
            name='plantsensordetail',
            unique_together=set([('plant_sensor', 'kode')]),
        ),
        migrations.AlterUniqueTogether(
            name='plantcontroldetail',
            unique_together=set([('plant_control', 'kode')]),
        ),
    ]
