# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantbase',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
    ]
