# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0002_plantevalif_prior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantevalif',
            options={'ordering': ['prior'], 'verbose_name': 'Evaluasi Tanaman (IF)'},
        ),
    ]
