# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0002_auto_20171104_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcontrollog',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('R', 'Read')], max_length=2, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='plantsensorlog',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('R', 'Read')], max_length=2, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plantcontroldetail',
            name='plant_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControl', verbose_name='Kontrol Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantcontrollog',
            name='plant_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControl', verbose_name='Kontrol Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantcontrollog',
            name='plant_rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantcontrollogdetail',
            name='plant_control_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControlLog', verbose_name='Log Kontrol Tanaman'),
        ),
        migrations.AlterField(
            model_name='planteval',
            name='plant_eval_if',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEvalIf', verbose_name='Evaluasi Tanaman (IF)'),
        ),
        migrations.AlterField(
            model_name='planteval',
            name='plant_eval_then',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEvalThen', verbose_name='Evaluasi Tanaman (THEN)'),
        ),
        migrations.AlterField(
            model_name='plantevallog',
            name='plant_eval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEval', verbose_name='Evaluasi Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantopt',
            name='plant_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantPlant', verbose_name='Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantoptdetail',
            name='plant_opt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantOpt', verbose_name='Kondisi Optimal Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantrack',
            name='plant_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantControl', verbose_name='Kontrol Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantrack',
            name='plant_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensor', verbose_name='Sensor Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantrackpoint',
            name='plant_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantPlant', verbose_name='Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantrackpoint',
            name='plant_rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantsensordetail',
            name='plant_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensor', verbose_name='Sensor Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='plant_rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='plant_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensor', verbose_name='Sensor Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantsensorlogdetail',
            name='plant_sensor_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantSensorLog', verbose_name='Log Sensor Tanaman'),
        ),
    ]
