# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0003_auto_20171210_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontrollog',
            name='dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Waktu'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Waktu'),
        ),
    ]
