# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0004_auto_20180817_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontrollog',
            name='plant_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sihipo_root.PlantControl', verbose_name='Kontrol Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantcontrollog',
            name='plant_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantcontrollogdetail',
            name='plant_control_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sihipo_root.PlantControlLog', verbose_name='Log Kontrol Tanaman'),
        ),
        migrations.AlterField(
            model_name='planteval',
            name='plant_eval_if',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEvalIf', verbose_name='Kondisi'),
        ),
        migrations.AlterField(
            model_name='planteval',
            name='plant_eval_then',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEvalThen', verbose_name='Aksi'),
        ),
        migrations.AlterField(
            model_name='plantevalif',
            name='eval_if',
            field=models.TextField(unique=True, verbose_name='Kode Python'),
        ),
        migrations.AlterField(
            model_name='plantevalif',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Kondisi'),
        ),
        migrations.AlterField(
            model_name='plantevalif',
            name='prior',
            field=models.IntegerField(default=10, unique=True, verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='plantevallog',
            name='plant_eval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sihipo_root.PlantEval', verbose_name='Evaluasi Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantevalthen',
            name='eval_then',
            field=models.TextField(unique=True, verbose_name='Kode Python'),
        ),
        migrations.AlterField(
            model_name='plantevalthen',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Aksi'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='plant_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='plant_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sihipo_root.PlantSensor', verbose_name='Sensor Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantsensorlogdetail',
            name='plant_sensor_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sihipo_root.PlantSensorLog', verbose_name='Log Sensor Tanaman'),
        ),
    ]
