# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0005_plantevallog_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAlert',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Waktu')),
                ('state', models.CharField(blank=True, choices=[(None, 'N/A'), ('N', 'Notice'), ('W', 'Warning'), ('S', 'Severe')], max_length=2, null=True, verbose_name='Status')),
            ],
            options={
                'ordering': ['-dt'],
                'verbose_name': 'Log Berita Tanaman',
            },
            bases=('sihipo_root.plantbase',),
        ),
    ]
