# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0006_plantalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantalert',
            options={'ordering': ['-dt'], 'verbose_name': 'Berita Tanaman'},
        ),
        migrations.AddField(
            model_name='plantalert',
            name='url',
            field=models.URLField(default='#', verbose_name='URL Aksi'),
        ),
    ]
