# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0007_plantbase_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantEvalGroup',
            fields=[
                ('plantbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sihipo_root.PlantBase')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Group')),
            ],
            bases=('sihipo_root.plantbase',),
        ),
        migrations.AlterModelOptions(
            name='plantevalif',
            options={'ordering': ['plant_eval_group', 'prior'], 'verbose_name': 'Kondisi'},
        ),
        migrations.AlterField(
            model_name='plantevalif',
            name='prior',
            field=models.IntegerField(default=10, verbose_name='Prioritas'),
        ),
        migrations.AddField(
            model_name='plantevalif',
            name='plant_eval_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantEvalGroup', verbose_name='Group'),
        ),
        migrations.AlterUniqueTogether(
            name='plantevalif',
            unique_together=set([('plant_eval_group', 'prior')]),
        ),
    ]
