# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0007_auto_20180114_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontrollog',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('P', 'Progress'), ('C', 'Complete')], max_length=2, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('P', 'Progress'), ('C', 'Complete')], max_length=2, null=True, verbose_name='Status'),
        ),
    ]
