# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0008_auto_20180128_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantalert',
            name='url',
            field=models.CharField(default='#', max_length=255, verbose_name='URL Aksi'),
        ),
    ]
