# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0008_auto_20180907_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantevalgroup',
            options={'verbose_name': 'Group Logika'},
        ),
    ]
