# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0009_auto_20180907_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantevalthen',
            name='eval_then',
            field=models.TextField(default='# Gunakan __exec__ untuk mengembalikan nilai', unique=True, verbose_name='Kode Python'),
        ),
    ]
