# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0010_auto_20180129_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantbase',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
    ]
