# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0011_auto_20180129_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantevallog',
            options={'ordering': ['-dt'], 'verbose_name': 'Log Evaluasi Tanaman'},
        ),
    ]
