# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0011_auto_20180930_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontroldetail',
            name='val',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('L', 'GROW LAMP'), ('S', 'SPRAY'), ('W', 'WATER PUMP'), ('A', 'AERIAL'), ('B', 'BLOWER'), ('M', 'MIXER')], max_length=2, null=True, verbose_name='Nilai'),
        ),
    ]
