# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0012_auto_20180401_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontrollog',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('P', 'To Do / Progress'), ('C', 'Done / Complete')], max_length=2, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('D', 'Draft'), ('P', 'To Do / Progress'), ('C', 'Done / Complete')], max_length=2, null=True, verbose_name='Status'),
        ),
    ]
