# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0012_auto_20181105_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontrollogdetail',
            name='val',
            field=models.IntegerField(choices=[(0, 'Normally Close'), (1, 'Normally Open'), (2, 'Toggle')], default=0, verbose_name='Nilai'),
        ),
    ]
