# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0013_auto_20181105_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantevalthen',
            options={'ordering': ['kode'], 'verbose_name': 'Aksi'},
        ),
    ]
