# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0013_auto_20180401_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontrollog',
            name='plant_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
        migrations.AlterField(
            model_name='plantsensorlog',
            name='plant_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sihipo_root.PlantRack', verbose_name='Rak Tanaman'),
        ),
    ]
