# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0014_auto_20181106_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantevalthen',
            options={'ordering': ['-active', 'kode'], 'verbose_name': 'Aksi'},
        ),
    ]
