# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0014_auto_20180402_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontroldetail',
            name='kode',
            field=models.CharField(choices=[(None, 'N/A'), ('D0', 'Digital 0'), ('D1', 'Digital 1'), ('D2', 'Digital 2'), ('D3', 'Digital 3'), ('D4', 'Digital 4'), ('D5', 'Digital 5'), ('D6', 'Digital 6'), ('D7', 'Digital 7')], max_length=3, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='plantcontrollogdetail',
            name='kode',
            field=models.CharField(choices=[(None, 'N/A'), ('D0', 'Digital 0'), ('D1', 'Digital 1'), ('D2', 'Digital 2'), ('D3', 'Digital 3'), ('D4', 'Digital 4'), ('D5', 'Digital 5'), ('D6', 'Digital 6'), ('D7', 'Digital 7')], max_length=3, verbose_name='Kode'),
        ),
    ]
