# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0015_auto_20181106_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantalert',
            options={'ordering': ['-active', '-dt'], 'verbose_name': 'Berita Tanaman'},
        ),
        migrations.AlterModelOptions(
            name='plantbase',
            options={'ordering': ['-active']},
        ),
        migrations.AlterModelOptions(
            name='plantcontrollog',
            options={'ordering': ['-active', '-dt'], 'verbose_name': 'Log Kontrol Tanaman'},
        ),
        migrations.AlterModelOptions(
            name='plantevalif',
            options={'ordering': ['-active', 'plant_eval_group', 'prior'], 'verbose_name': 'Kondisi'},
        ),
        migrations.AlterModelOptions(
            name='plantevallog',
            options={'ordering': ['-active', '-dt'], 'verbose_name': 'Log Evaluasi Tanaman'},
        ),
        migrations.AlterModelOptions(
            name='plantevalthen',
            options={'ordering': ['-active', '-active', 'kode'], 'verbose_name': 'Aksi'},
        ),
        migrations.AlterModelOptions(
            name='plantsensorlog',
            options={'ordering': ['-active', '-dt'], 'verbose_name': 'Log Sensor Tanaman'},
        ),
    ]
