# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0016_auto_20190105_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrack',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('NFT', 'NFT'), ('DFT', 'DFT'), ('WICK', 'Wick')], max_length=4, null=True, verbose_name='Type'),
        ),
    ]
