# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0017_auto_20190116_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantoptdetail',
            name='kode',
            field=models.CharField(choices=[(None, 'N/A'), ('PH', 'Keasaman (pH)'), ('EC', 'Konduktifitas (mS/cm)'), ('HT', 'Kelembapan (%)'), ('TW', 'Suhu Air (C)'), ('TA', 'Suhu Udara (C)'), ('LW', 'Level Air'), ('BL', 'Level Baterai (%)'), ('PA', 'Usia Tanam (Hari)')], max_length=3, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='plantsensordetail',
            name='kode',
            field=models.CharField(choices=[(None, 'N/A'), ('PH', 'Keasaman (pH)'), ('EC', 'Konduktifitas (mS/cm)'), ('HT', 'Kelembapan (%)'), ('TW', 'Suhu Air (C)'), ('TA', 'Suhu Udara (C)'), ('LW', 'Level Air'), ('BL', 'Level Baterai (%)'), ('PA', 'Usia Tanam (Hari)')], max_length=3, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='plantsensorlogdetail',
            name='kode',
            field=models.CharField(choices=[(None, 'N/A'), ('PH', 'Keasaman (pH)'), ('EC', 'Konduktifitas (mS/cm)'), ('HT', 'Kelembapan (%)'), ('TW', 'Suhu Air (C)'), ('TA', 'Suhu Udara (C)'), ('LW', 'Level Air'), ('BL', 'Level Baterai (%)'), ('PA', 'Usia Tanam (Hari)')], max_length=3, verbose_name='Kode'),
        ),
    ]
