# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0018_auto_20190402_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdevice',
            name='url',
            field=models.URLField(verbose_name='URL Device'),
        ),
        migrations.AlterUniqueTogether(
            name='plantdevice',
            unique_together=set([('url', 'tipe')]),
        ),
    ]
