# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihipo_root', '0020_auto_20190705_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcontroldetail',
            name='val',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('L', 'GROW LAMP'), ('D', 'DAY LAMP'), ('S', 'SPRAY'), ('W', 'WATER PUMP'), ('A', 'AERIAL'), ('B', 'BLOWER'), ('M', 'MIXER')], max_length=2, null=True, verbose_name='Nilai'),
        ),
    ]
