from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^plantplant/$', views.PlantPlantList.as_view(), name='plantplant_list'),
    url(r'^plantplant/create$', views.PlantPlantCreate.as_view(), name='plantplant_create'),
    url(r'^plantplant/update/(?P<pk>\d+)$', views.PlantPlantUpdate.as_view(), name='plantplant_update'),
    url(r'^plantplant/delete/(?P<pk>\d+)$', views.PlantPlantDelete.as_view(), name='plantplant_delete'),
    url(r'^plantopt/$', views.PlantOptList.as_view(), name='plantopt_list'),
    url(r'^plantopt/create$', views.PlantOptCreate.as_view(), name='plantopt_create'),
    url(r'^plantopt/update/(?P<pk>\d+)$', views.PlantOptUpdate.as_view(), name='plantopt_update'),
    url(r'^plantopt/delete/(?P<pk>\d+)$', views.PlantOptDelete.as_view(), name='plantopt_delete'),
    url(r'^plantoptdetail/$', views.PlantOptDetailList.as_view(), name='plantoptdetail_list'),
    url(r'^plantoptdetail/create/$', views.PlantOptDetailCreate.as_view(), name='plantoptdetail_create'),
    url(r'^plantoptdetail/update/(?P<pk>\d+)$', views.PlantOptDetailUpdate.as_view(), name='plantoptdetail_update'),
    url(r'^plantoptdetail/delete/(?P<pk>\d+)$', views.PlantOptDetailDelete.as_view(), name='plantoptdetail_delete'),
    url(r'^plantsensor/$', views.PlantSensorList.as_view(), name='plantsensor_list'),
    url(r'^plantsensor/create/$', views.PlantSensorCreate.as_view(), name='plantsensor_create'),
    url(r'^plantsensor/update/(?P<pk>\d+)$', views.PlantSensorUpdate.as_view(), name='plantsensor_update'),
    url(r'^plantsensor/delete/(?P<pk>\d+)$', views.PlantSensorDelete.as_view(), name='plantsensor_delete'),
    url(r'^plantsensordetail/$', views.PlantSensorDetailList.as_view(), name='plantsensordetail_list'),
    url(r'^plantsensordetail/create/$', views.PlantSensorDetailCreate.as_view(), name='plantsensordetail_create'),
    url(r'^plantsensordetail/update/(?P<pk>\d+)$', views.PlantSensorDetailUpdate.as_view(), name='plantsensordetail_update'),
    url(r'^plantsensordetail/delete/(?P<pk>\d+)$', views.PlantSensorDetailDelete.as_view(), name='plantsensordetail_delete'),
    url(r'^plantcontrol/$', views.PlantControlList.as_view(), name='plantcontrol_list'),
    url(r'^plantcontrol/create/$', views.PlantControlCreate.as_view(), name='plantcontrol_create'),
    url(r'^plantcontrol/update/(?P<pk>\d+)$', views.PlantControlUpdate.as_view(), name='plantcontrol_update'),
    url(r'^plantcontrol/delete/(?P<pk>\d+)$', views.PlantControlDelete.as_view(), name='plantcontrol_delete'),
    url(r'^plantcontroldetail/$', views.PlantControlDetailList.as_view(), name='plantcontroldetail_list'),
    url(r'^plantcontroldetail/create/$', views.PlantControlDetailCreate.as_view(), name='plantcontroldetail_create'),
    url(r'^plantcontroldetail/update/(?P<pk>\d+)$', views.PlantControlDetailUpdate.as_view(), name='plantcontroldetail_update'),
    url(r'^plantcontroldetail/delete/(?P<pk>\d+)$', views.PlantControlDetailDelete.as_view(), name='plantcontroldetail_delete'),
    url(r'^plantrack/$', views.PlantRackList.as_view(), name='plantrack_list'),
    url(r'^plantrack/create/$', views.PlantRackCreate.as_view(), name='plantrack_create'),
    url(r'^plantrack/update/(?P<pk>\d+)$', views.PlantRackUpdate.as_view(), name='plantrack_update'),
    url(r'^plantrack/delete/(?P<pk>\d+)$', views.PlantRackDelete.as_view(), name='plantrack_delete'),
    url(r'^plantrackpoint/$', views.PlantRackPointList.as_view(), name='plantrackpoint_list'),
    url(r'^plantrackpoint/create/$', views.PlantRackPointCreate.as_view(), name='plantrackpoint_create'),
    url(r'^plantrackpoint/update/(?P<pk>\d+)$', views.PlantRackPointUpdate.as_view(), name='plantrackpoint_update'),
    url(r'^plantrackpoint/delete/(?P<pk>\d+)$', views.PlantRackPointDelete.as_view(), name='plantrackpoint_delete'),
]